{
 "title": "MAAS Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "maas_id", "label": "MAAS ID", "query": { "query": "label_values(maas_id)" } },
   { "name": "cidr", "query": { "query": "label_values(cidr)" } },
   { "name": "node", "query": { "query": "label_values(host)" } },
   { "name": "racks", "query": { "query": "label_values(system_id)" } },
   { "name": "maas_vip", "query": "127.0.0.1" },
   {
    "name": "status_code",
    "query": "400,401,403,404,409,500,501,503"
   }
  ]
 },
 "panels": [
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region/Rack Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{maas_id=\"$maas_id\",type=\"regionracks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{maas_id=\"$maas_id\",type=\"regions\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rack Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(maas_nodes{maas_id=\"$maas_id\",type=\"racks\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Racks Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rack Services Status (system_id=$racks)",
   "type": "stat",
   "description": "Show the rack services that are in a {Off, Dead, Unknown} status.\nServices that are in an \"ON\" status are not shown.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "repeat": "racks",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk by(service, system_id) (1, sort_desc(maas_service_availability{maas_id=\"$maas_id\", system_id=\"$racks\", pid=\"\"}) != 1)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "MAAS Node Status (${node:raw})", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "node" },
  {
   "title": "CPU usage ($node)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*((sum(rate(maas_node_cpu_time_total{maas_id=\"$maas_id\",host=\"${node:raw}\"}[$__rate_interval])) - sum(rate(maas_node_cpu_time_total{maas_id=\"$maas_id\",host=\"${node:raw}\", state=\"idle\"}[$__rate_interval])))) / sum(rate(maas_node_cpu_time_total{maas_id=\"$maas_id\",host=\"${node:raw}\"}[$__rate_interval]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "CPU time ($node)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 16 },
   "targets": [
    {
     "expr": "rate(maas_node_cpu_time_total{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}[$__rate_interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "RAM usage ($node)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(pid) (1 - (last_over_time(maas_node_mem_MemFree{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}[$__interval])/last_over_time(maas_node_mem_MemTotal{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}[$__interval])))",
     "legendFormat": "RAM Usage"
    }
   ]
  },
  {
   "title": "Memory distribution ($node)",
   "type": "timeseries",
   "description": "Memory distribution values taken from /proc/meminfo",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum without(pid) (maas_node_mem_Buffers{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_SwapCached{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Swap Cached"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_Slab{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Slab"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_PageTables{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Page Tables"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_AnonPages{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Anonymous"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_Shmem{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Shared memory smallpages"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_Cached{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}-maas_node_mem_Shmem{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Mapped and Cached"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_MemFree{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "sum without(pid) ((maas_node_mem_HugePages_Free{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}-maas_node_mem_HugePages_Rsvd{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})*2048)",
     "legendFormat": "Hugepages Free"
    },
    {
     "expr": "sum without(pid) (maas_node_mem_HugePages_Rsvd{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}*2048)",
     "legendFormat": "Hugepages Reserved"
    },
    {
     "expr": "sum without(pid) ((sum(maas_node_mem_HugePages_Total{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"})-sum(maas_node_mem_HugePages_Free{maas_id=\"$maas_id\", host=\"${node:raw}\", service_type=\"region\"}))*2048)",
     "legendFormat": "Hugepages Used"
    }
   ]
  },
  { "title": "RPC Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Rack -> Region calls avg latency",
   "type": "timeseries",
   "description": "Average latency of rack to region rpc calls in $__rate_interval interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_rack_region_rpc_call_latency_sum{maas_id=\"$maas_id\"}[$__rate_interval])) /\nsum by(call) (rate(maas_rack_region_rpc_call_latency_count{maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rack -> Region calls latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (call) (rate(maas_rack_region_rpc_call_latency_sum{maas_id=\"$maas_id\"}[$__rate_interval])) /\nsum by (call) (rate(maas_rack_region_rpc_call_latency_count{maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, call) (rate(maas_rack_region_rpc_call_latency_bucket[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.0001, sum by(call, le) (rate(maas_rack_region_rpc_call_latency_bucket[$__rate_interval])))",
     "legendFormat": "min"
    }
   ]
  },
  {
   "title": "Region -> Rack calls avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(maas_region_rack_rpc_call_latency_sum{maas_id=\"$maas_id\"}[$__rate_interval])) by(call) / \nsum(rate(maas_region_rack_rpc_call_latency_count{maas_id=\"$maas_id\"}[$__rate_interval])) by(call)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region -> Rack calls",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(call) (rate(maas_region_rack_rpc_call_latency_sum{maas_id=\"$maas_id\"}[$__rate_interval])) /\nsum by(call) (rate(maas_region_rack_rpc_call_latency_count{maas_id=\"$maas_id\"}[$__rate_interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, call) (rate(maas_region_rack_rpc_call_latency_bucket[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.0001, sum by(le, call) (rate(maas_region_rack_rpc_call_latency_bucket[$__rate_interval])))",
     "legendFormat": "min"
    }
   ]
  },
  { "title": "API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Machine Listing percentiles (v2)",
   "type": "timeseries",
   "description": "Time necessary to fetch machines through the v2 API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{maas_id=\"$maas_id\", handler=\"/api/v2/machines\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{maas_id=\"$maas_id\", handler=\"/api/v2/machines\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, handler) (rate(maas_apiserver_request_latency_bucket{maas_id=\"$maas_id\", handler=\"/api/v2/machines\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Machine Listing percentiles (WS)",
   "type": "timeseries",
   "description": "Time necessary to fetch machines through websockets. Includes a call to the v2 machine listing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, call) (rate(maas_websocket_call_latency_bucket{maas_id=\"$maas_id\", call=\"machine.list\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, call) (rate(maas_websocket_call_latency_bucket{maas_id=\"$maas_id\", call=\"machine.list\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, call) (rate(maas_websocket_call_latency_bucket{maas_id=\"$maas_id\", call=\"machine.list\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "4xx/5xx responses count (last 30m)",
   "type": "stat",
   "description": "API calls with error status codes, grouped by status code, in the last 30 minutes.\nClick on a value to visualize which API calls are failing.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (round(increase(maas_http_request_latency_count{maas_id=\"$maas_id\", status=~\"[4,5][0-9]{2}\"}[30m]), 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(status) (round(increase(maas_apiserver_request_latency_count{maas_id=\"$maas_id\", status=~\"[4,5][0-9]{2}\"}[30m]), 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API calls with $status_code response ",
   "type": "stat",
   "description": "Shows which API calls are failing with the specified status code. To modify the visualization (i.e. the status code) use the panel above.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 103 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method, path) (round(increase(maas_http_request_latency_count{maas_id=\"$maas_id\", status=\"$status_code\"}[30m]) > 0, 1)) ",
     "legendFormat": "{{method}} {{path}}"
    },
    {
     "expr": "sum by(method, handler) (round(increase(maas_apiserver_request_latency_count{maas_id=\"$maas_id\", status=\"$status_code\"}[30m]) > 0, 1))",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Machines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B - $A", "type": "math" },
    {
     "expr": "max(maas_kvm_machines{maas_id=\"$maas_id\"})",
     "legendFormat": "Virtual"
    },
    {
     "expr": "max(maas_nodes{maas_id=\"$maas_id\",type=\"machines\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 110 },
   "targets": [
    {
     "expr": "max(maas_nodes{maas_id=\"$maas_id\",type=\"devices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KVM Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 110 },
   "targets": [
    {
     "expr": "max(maas_kvm_pods{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Machines by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "max(maas_machines{maas_id=\"$maas_id\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Networks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Spaces",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_spaces{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fabrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_fabrics{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLANs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_vlans{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv4 subnets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_subnets_v4{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPv6 subnets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_subnets_v6{maas_id=\"$maas_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IPs availability (subnet: $cidr)",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 125 },
   "targets": [
    {
     "expr": "max(maas_net_subnet_ip_count{cidr=\"$cidr\",maas_id=\"$maas_id\",status=\"available\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "max(maas_net_subnet_ip_count{cidr=\"$cidr\",maas_id=\"$maas_id\",status=\"unavailable\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  { "title": "KVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "Cores",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "avg(maas_kvm_cores{maas_id=\"$maas_id\"}) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "avg(maas_kvm_overcommit_cores{maas_id=\"$maas_id\"})",
     "legendFormat": "available with vercommit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "avg(maas_kvm_memory{maas_id=\"$maas_id\"}) by (status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(maas_kvm_overcommit_memory{maas_id=\"$maas_id\"})",
     "legendFormat": "available with overcommit"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(maas_kvm_storage{maas_id=\"$maas_id\"}) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}